CREATE TABLE IF NOT EXISTS capacity_catalogs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    external_id BIGINT NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);